# Generated by Django 5.0.3 on 2024-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('comment', models.TextField(default=None)),
            ],
        ),
    ]
