# Generated by Django 5.0.3 on 2024-03-05 02:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=40, unique=True)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(default=None, max_length=300)),
                ('isSeller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=40)),
                ('Image', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('discount', models.FloatField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
    ]
