# Generated by Django 5.0.3 on 2024-03-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_user_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
