# Generated by Django 5.0.3 on 2024-03-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_order_productorders_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='order',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
