# Generated by Django 5.0.3 on 2024-03-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_productorders_order_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorders',
            name='product',
        ),
    ]
